# Generated by Django 5.1.5 on 2025-04-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='description',
            new_name='desc',
        ),
    ]
