# Generated by Django 5.1.5 on 2025-04-14 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Уникальный ключ алгоритма', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Название алгоритма', max_length=255)),
                ('type', models.CharField(help_text='Тип алгоритма', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aibox_alert_id', models.CharField(max_length=255, unique=True)),
                ('alert_time', models.DateTimeField()),
                ('hazard_level', models.CharField(default='1', help_text='Уровень опасности')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', help_text='Статус тревоги', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Время подтверждения тревоги', null=True)),
                ('rejected_at', models.DateTimeField(blank=True, help_text='Время отклонения тревоги', null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('company', models.ForeignKey(help_text='Компания, связанная с тревогой', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='companies.company')),
            ],
        ),
    ]
