# Generated by Django 5.1.5 on 2025-04-14 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('algorithms', '0001_initial'),
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='device',
            field=models.ForeignKey(help_text='AIBox-устройство', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.device'),
        ),
        migrations.AddField(
            model_name='alert',
            name='executive_users',
            field=models.ManyToManyField(blank=True, help_text='Учредители', related_name='executive_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.ForeignKey(help_text='Источник (камера)', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.source'),
        ),
        migrations.AddField(
            model_name='alert',
            name='alg',
            field=models.ForeignKey(blank=True, help_text='Алгоритм, сработавший на тревогу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='algorithms.algorithm'),
        ),
    ]
