# Generated by Django 5.1.5 on 2025-04-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение тревоги (если есть)', null=True, upload_to='alerts/images/'),
        ),
        migrations.AddField(
            model_name='alert',
            name='reserved_data',
            field=models.JSONField(blank=True, help_text='Дополнительные данные от AIBox', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='video',
            field=models.FileField(blank=True, help_text='Видео тревоги (если есть)', null=True, upload_to='alerts/videos/'),
        ),
    ]
