# Generated by Django 5.1.5 on 2025-04-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0003_alert_image_alert_reserved_data_alert_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='image_url',
        ),
    ]
